source ~/.profile
source ~/dotfiles/links/bash/aliases
source ~/dotfiles/links/bash/functions
INPUTRC="~/dotfiles/links/bash/inputrc"
# Must import functions before bashrc
source ~/dotfiles/links/bashrc

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
