source ~/.profile
source ~/dotfiles/links/bash/aliases
source ~/dotfiles/links/bash/functions
source ~/dotfiles/links/bash/inputrc
# Must import functions before bashrc
source ~/dotfiles/links/bashrc

