#!usr/bin/env bash

# https://stackoverflow.com/questions/4642822/commands-executed-from-vim-are-not-recognizing-bash-command-aliases
shopt -s expand_aliases

#################################################
#################### Aliases ####################
#################################################

alias c='clear'
alias tree="tree -C" # Colorize tree

# reload profile
alias reload='. ~/.bashrc >/dev/null && echo "reloaded"'

# -F displays `/`for directories, `*` for executables, etc...
alias ls='ls -F'
alias ls.='ls -Fd .*' # Show dotfiles and hide others
alias ll='ls -aoFh' # Show all files and directories with sizes
alias lsa='ls -a' # show all files and directories
alias ~="cd ~" # Make it easier to go to root
alias dot="cd ~/dotfiles"

# Git
alias g="git"
alias ga="git add"
alias gap="git add --patch"
alias gc="git commit -m"
alias gp="git push"
alias gd="git diff"
alias gdc="git diff --cached" # show added but uncommited changes
alias gs="git status"
alias gb="git branch"
alias gdb="git branch -d"
alias gsb="git checkout" # stands for git switch branch

# For going up multiple directories
alias cd..='cd ..' # For mistyping
alias .1='cd ..'
alias .2='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'

# Track CPU usage
alias cpu="top -F -R -o cpu"

# Open applications
alias chrome="open -a 'Google Chrome'"
alias spotify="open -a Spotify"

# LaTeX Cleanup
alias cleantex="find . \( -name '*.log' -or -name '*.synctex.gz' -or -name '*.fdb_latexmk' -or -name '*.fls' -or -name '*.aux' \) -delete"

### Python
# Open virtual environment
alias mkvenv="python3 -m venv venv"
alias venv="source venv/bin/activate"
alias xvenv="deactivate venv"
alias jn="jupyter notebook"
alias jvenv="ipython kernel install --user --name=" # include name of kernel as arg
alias py="python"
alias py3="python3"
alias py37="python3.7"
alias ipy="ipython"
