name: Smoke Test
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Print current working directory
        run: pwd
      - name: List files/folders in directory
        run: ls
      - name: Run bootstrap.sh
        run: ./bootstrap.sh
