name: Smoke Test
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Print current working directory
        run: pwd
      - name: Tree
        run: tree
      - name: Run bootstrap.sh
        run: ./bootstrap.sh
