name: Smoke Test
on:
  - push
  - pull_request

jobs:
  build-macOS-latest:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Make bootstrap.sh executable
        run: chmod +x ./bootstrap.sh
      - name: Run bootstrap.sh
        run: |
          ./bootstrap.sh --testing
  build-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Make bootstrap.sh executable
        run: chmod +x ./bootstrap.sh
      - name: Run bootstrap.sh
        run: |
          sudo ./bootstrap.sh --testing
