name: Smoke Test
on: [push]

jobs:
  build-macOS-latest:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run bootstrap.sh
        run: |
          ./bootstrap.sh
  build-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run bootstrap.sh
        run: |
          ./bootstrap.sh
