name: Smoke Test
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Print directory contents above
        run: ls ../..
      - name: Run bootstrap.sh
        run: ../bootstrap.sh
